### ISSUE TITLE
logs for CI test

### ISSUE THREAD

**Issue by johncoleman83** [johncoleman83/cerebrum#41]
utilize something like 
```
      - store_artifacts:
          path: log
          destination: test.log
      - store_test_results:
          path: test
```

To be able to access logs from CI
